### PR TITLE
Added Targeting Info to Flutter Admob

### PR DESCRIPTION
**Pull request by yiss**
Once the PR is reviewed I can bump the version

### CODE REVIEW

**Comment by EliasDeuss** [comment]
@yiss Looks like you added so deprecated values for targeting info.

**Comment by yiss** [comment]
@EliasDeuss I copied the same code from the official firebase_admob repository. From what've read the target info API is deprecated in favor of RequestConfiguration. But the API still works for now.

**Comment by yiss** [comment]
@EliasDeuss you can check the documentation here : https://developers.google.com/admob/android/targeting I can adapt it afterwards to work properly with the new API, but I think for now this seems to be the best thing

**Comment by kmcgill88** [comment]
@yiss I am actively working on a branch that add's support for `testDevices` and I'm using the new api's `RequestConfiguration`. I've also refactored iOS's rewards ads to use it's new API. 

Please refactor this PR to drop all deprecated things and adopt the new API(s). I plan on merging my branch tonight, https://github.com/kmcgill88/admob_flutter/tree/support-device-test-ids

ps. be sure to pull master. `pedantic` has been updated and your lint rules will surely fail CI if you don't.

**Comment by kmcgill88** [comment]
Also, I'm planning on including targeting into `1.0.0-beta.3` so if you introduce breaking changes, that's ok. There are going to be a few other breaking changes which is why I'm bumping this to `1.0.0-beta.x`

**Comment by yiss** [comment]
@kmcgill88 ok I'll make sure I'll do that, for the `RequestConfiguration` API do you have a special implementation for the `InterstialAds` maybe it can be passed in the `load(requestConf: RequestConfiguration)` or should it be in the constructor.
For the RewardsAds I'm not sure I'll have the time to do it fast. But I'll see, also I was thinking maybe moving to the PluginApi ? and Implementing native ads maybe something like : https://pub.dev/packages/flutter_native_admob

**Comment by kmcgill88** [comment]
@yiss Good question on where to pass the target config. I think it could be nice to pass in the [constructor](https://github.com/kmcgill88/admob_flutter/blob/master/lib/src/admob_interstitial.dart#L16) when you want the same targeting info applied to all requests. Maybe sometime also allowing passing target info as an arg to [load](https://github.com/kmcgill88/admob_flutter/blob/master/lib/src/admob_interstitial.dart#L35) which would take priority over the constructor would be cool. That way you could have more control over targeting per load. In both cases I would make the new argument optional.

**Comment by davidmartos96** [comment]
Any update on this PR? It looked very promising.

**Comment by kmcgill88** [comment]
@yiss think you will have time to get this PR cleaned up to be merged anytime soon? I would like to get this merged into a beta version and hopefully soonish get the official `1.0.0` out the door.

**Comment by yiss** [comment]
Hi @kmcgill88, Sorry was a bit off for a bit but yeah I'll try to fix the comments tomorrow. Do you have a specific Date for the 1.0.0 release ?

**Pull request closed without merging**
